import {
  IoSpeedometerOutline,
  IoCheckboxOutline,
  IoPersonCircleOutline
} from "react-icons/io5";

export default [
  {
    text: "Dashboard",
    link: "/",
    type: "menu",
    exact: true,
    icon: <IoSpeedometerOutline />,
    hak: [
      "HRDU",
      "ASM",
      "MKT",
      "CRM",
      "INV",
      "ANG",
      "HRDA",
      "HRDU_APR_PRO",
      "HRDU_APR_RP",
      "HRDU_APR_REGKEG",
      "HRDU_APR_PR",
      "HRDU_APR_REGRAB",
      "HRDU_APR_REGPNW",
      "HRDU_APR_PVSPR",
      "HRDU_APR_REGPRO",
      "HRDU_APR_PENPO",
      "HRDU_APR_REGFPNJ",
      "HRDU_APR_PENFPNJ",
      "HRDU_APR_REGDO",
      "HRDU_APR_REGPO",
      "HRDU_APR_REGRAE",
      "HRDU_APR_REGRAP",
      "HRDU_APR_REGSJ",
      "HRDU_APR_REGSO",
      "HRDU_APR_REGSPK",
      "HRDU_APR_RK",
      "HRDU_APR_REGPPA",
      "HRDU_APR_MAG"
    ],
  },
  {
    text: "Approval",
    type: "dropdown",
    icon: <IoCheckboxOutline />,
    hak: [
      "HRDU",
      "HRDU_APR_PRO",
      "HRDU_APR_RP",
      "HRDU_APR_REGKEG",
      "HRDU_APR_PR",
      "HRDU_APR_REGRAB",
      "HRDU_APR_REGPNW",
      "HRDU_APR_PVSPR",
      "HRDU_APR_REGPRO",
      "HRDU_APR_PENPO",
      "HRDU_APR_REGFPNJ",
      "HRDU_APR_PENFPNJ",
      "HRDU_APR_REGDO",
      "HRDU_APR_REGPO",
      "HRDU_APR_REGRAE",
      "HRDU_APR_REGRAP",
      "HRDU_APR_REGSJ",
      "HRDU_APR_REGSO",
      "HRDU_APR_REGSPK",
      "HRDU_APR_RK",
      "HRDU_APR_REGPPA",
      "HRDU_APR_MAG"
    ],
    menu: [
      {
        text: "Program",
        link: "/human-resource/approval/program",
        hak: ["HRDU", "HRDU_APR_REGPRG"],
      },
      {
        text: "Kegiatan",
        link: "/human-resource/approval/kegiatan",
        hak: ["HRDU", "HRDU_APR_REGKEG", "HRDU_APR_RK"],
      },
      {
        text: "Sub Kegiatan",
        link: "/human-resource/approval/sub-kegiatan",
        hak: ["HRDU", "HRDU_APR_REGPPA"],
      },
      {
        text: "RKA",
        link: "/human-resource/approval/rka",
        hak: ["HRDU", "HRDU_APR_REGRAE"],
      },
      {
        text: "PPA",
        link: "/human-resource/approval/ppa",
        hak: ["HRDU", "HRDU_APR_REGRAE"],
      },
    ],
  },
  {
    text: "Profil",
    type: "dropdown",
    icon: <IoPersonCircleOutline />,
    hak: [
      "HRDU",
      "ASM",
      "MKT",
      "CRM",
      "INV",
      "ANG",
      "HRDA",
      "HRDU_APR_KEG",
      "HRDU_APR_PR",
      "HRDU_APR_REGRAB",
      "HRDU_APR_REGPNW",
      "HRDU_APR_PVSPR",
      "HRDU_APR_REGPRO",
      "HRDU_APR_PENPO",
      "HRDU_APR_REGFPNJ",
      "HRDU_APR_PENFPNJ",
      "HRDU_APR_REGDO",
      "HRDU_APR_REGPO",
      "HRDU_APR_REGRAE",
      "HRDU_APR_REGRAP",
      "HRDU_APR_REGSJ",
      "HRDU_APR_REGSO",
      "HRDU_APR_REGSPK",
      "HRDU_APR_RK",
      "HRDU_APR_REGPPA",
      "HRDU_APR_MAG"
    ],
    menu: [
      {
        text: "Akun Saya",
        link: "/profil",
        hak: [
          "HRDU",
          "ASM",
          "MKT",
          "CRM",
          "INV",
          "ANG",
          "HRDA",
          "HRDU_APR_KEG",
          "HRDU_APR_PR",
          "HRDU_APR_REGRAB",
          "HRDU_APR_REGPNW",
          "HRDU_APR_PVSPR",
          "HRDU_APR_REGPRO",
          "HRDU_APR_PENPO",
          "HRDU_APR_REGFPNJ",
          "HRDU_APR_PENFPNJ",
          "HRDU_APR_REGDO",
          "HRDU_APR_REGPO",
          "HRDU_APR_REGRAE",
          "HRDU_APR_REGRAP",
          "HRDU_APR_REGSJ",
          "HRDU_APR_REGSO",
          "HRDU_APR_REGSPK",
          "HRDU_APR_RK",
          "HRDU_APR_REGPPA",
          "HRDU_APR_MAG"
        ],
      },
      {
        text: "Ubah Akun",
        link: "/ubah-profil",
        hak: [
          "HRDU",
          "ASM",
          "MKT",
          "CRM",
          "INV",
          "ANG",
          "HRDA",
          "HRDU_APR_KEG",
          "HRDU_APR_PR",
          "HRDU_APR_REGRAB",
          "HRDU_APR_REGPNW",
          "HRDU_APR_PVSPR",
          "HRDU_APR_REGPRO",
          "HRDU_APR_PENPO",
          "HRDU_APR_REGFPNJ",
          "HRDU_APR_PENFPNJ",
          "HRDU_APR_REGDO",
          "HRDU_APR_REGPO",
          "HRDU_APR_REGRAE",
          "HRDU_APR_REGRAP",
          "HRDU_APR_REGSJ",
          "HRDU_APR_REGSO",
          "HRDU_APR_REGSPK",
          "HRDU_APR_RK",
          "HRDU_APR_REGPPA",
          "HRDU_APR_MAG"
        ],
      },
      {
        text: "Ganti Password",
        link: "/ganti-password",
        hak: [
          "HRDU",
          "ASM",
          "MKT",
          "CRM",
          "INV",
          "ANG",
          "HRDA",
          "HRDU_APR_KEG",
          "HRDU_APR_PR",
          "HRDU_APR_REGRAB",
          "HRDU_APR_REGPNW",
          "HRDU_APR_PVSPR",
          "HRDU_APR_REGPRO",
          "HRDU_APR_PENPO",
          "HRDU_APR_REGFPNJ",
          "HRDU_APR_PENFPNJ",
          "HRDU_APR_REGDO",
          "HRDU_APR_REGPO",
          "HRDU_APR_REGRAE",
          "HRDU_APR_REGRAP",
          "HRDU_APR_REGSJ",
          "HRDU_APR_REGSO",
          "HRDU_APR_REGSPK",
          "HRDU_APR_RK",
          "HRDU_APR_REGPPA",
          "HRDU_APR_MAG"
        ],
      },
    ],
  },
]
